filter:
    path:
        - 'rainloop-webmail/rainloop/v/0.0.0/app/libraries/MailSo/*'
        - 'rainloop-webmail/rainloop/v/0.0.0/app/libraries/RainLoop/*'
        - 'dev/*'
        - '/*.js'
    excluded_paths:
        - '*.min.js'
        - '*/min/*'
        - '*.min.css'
        - 'vendors/*'
        - 'build/*'
        - 'data/*'
checks:
    javascript: true
    php: true